// Test in place FFT
// Code here is modified from
// http://https://stackoverflow.com/questions/8801158/fft-in-a-single-c-file
// where it was an answer posted by Leos313

#include "./fft.h"
#include <iostream>
#include <random>
#include <iomanip>   // for print field width

using namespace std;

int check(int n) {   //checking if the number of element is a power of 2
    return n > 0 && (n & (n - 1)) == 0;
}

int log2(int N) {   // calculate the log2(.) of int
    int k = N, i = 0;
    while(k) { k >>= 1; i++;}
    return i - 1;
}

int old_reverse(int N, int n)    //calculating reverse number
{
  int j, p = 0;
  int lN = log2(N);
  for(j = 1; j <= lN; j++) {
    if(n & (1 << (lN - j)))
      p |= 1 << (j - 1);
  }
  return p;
}

void old_ordina(complex<double>* f1, int N) //using the reverse order in the array
{
  complex<double> f2[1 << MAXLG2];
  for(int i = 0; i < N; i++)
    f2[i] = f1[old_reverse(N, i)];
  for(int j = 0; j < N; j++)
    f1[j] = f2[j];
}

void old_transform(complex<double>* f, int lg2N) //
{
  int N = 1 << lg2N;
  old_ordina(f, N);    //first: reverse order
  complex<double> *W;
  W = (complex<double> *)malloc(N / 2 * sizeof(complex<double>));
  W[1] = polar(1., -2. * M_PI / N);
  W[0] = 1;
  for(int i = 2; i < N / 2; i++)
    W[i] = pow(W[1], i);
  int n = 1;
  int a = N / 2;
  for(int j = 0; j < lg2N; j++) {
    for(int i = 0; i < N; i++) {
      if(!(i & n)) {
        complex<double> temp = f[i];
        complex<double> Temp = W[(i * a) % (n * a)] * f[i + n];
        f[i] = temp + Temp;
        f[i + n] = temp - Temp;
      }
    }
    n *= 2;
    a = a / 2;
  }
  free(W);
}

void copyDComplex (complex<double>* from, complex<double>* to, int N) {
    for (int j = N; j;) {
        j--;
        to[j] = from[j];
    }
}

int main()
{
  int n, lg2;
  complex<double>* vec1 = NULL;
  complex<double>* vec2 = NULL;
  do {
    cout << "specify array dimension as a power of 2" << endl;
    cin >> lg2;
    cout << "log2 of that is " << lg2 << endl;
  } while((lg2 < 1) || (lg2 > MAXLG2));
  n = 1 << lg2;
  cout << "n = " << n << endl;

  // Test to see if new method agrees with old (almost original) method.
  if (vec1 == NULL) {
      cout << "allocating first vector of " << n << " complex values" << endl;
      if ((vec1 = (complex<double>*) malloc(sizeof(complex<double>) * n)) == NULL) {
          cout << "Failed allocation of space for sample data." << endl;
          exit(1);
      }
  }
  if (vec2 == NULL) {
      cout << "allocating second vector of " << n << " complex values" << endl;
      if ((vec2 = (complex<double>*) malloc(sizeof(complex<double>) * n)) == NULL) {
          cout << "Failed allocation of space for sample data." << endl;
          exit(1);
      }
  }
    std::random_device rd;  //Will be used to obtain a seed for the random number engine
    std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
    std::uniform_real_distribution<> dis(-10.0, 10.0);
    for (int j = 0; j < n; ++j) {
        // Use dis to transform the random unsigned int generated by gen into a 
        // double in [-10, 10). Each call to dis(gen) generates a new random double
        vec1[j] = dis(gen) + 1i * dis(gen);
    }
    copyDComplex(vec1, vec2, n);
    cout << "sample data\n";
    #define WIDTH (10)
    double sample_energy = 0.0;
    for (int j = 0; j < n; j++) {
        sample_energy += (real(vec1[j]) * real(vec1[j])) +
                         (imag(vec1[j]) * imag(vec1[j]));
        double rdiff = real(vec2[j]) - real(vec1[j]);
        double idiff = imag(vec2[j]) - imag(vec1[j]);
        cout << setw(WIDTH) << real(vec1[j]) << ",";
        cout << setw(WIDTH) << imag(vec1[j]) << "  ";
        cout << setw(WIDTH) << real(vec2[j]) << ",";
        cout << setw(WIDTH) << imag(vec2[j]) << "  ";
        cout << setw(WIDTH) << rdiff << ",";
        cout << setw(WIDTH) << idiff << endl;
    }
    old_transform(vec1, lg2); // replace line   FFT(vec, n, d);
    fft(vec2, lg2);
    cout << "FFT of the sample data" << endl;
    double errsqMax = 0.0;
    double xform_energy = 0.0;
    for(int j = 0; j < n; j++) {
        xform_energy += (real(vec1[j]) * real(vec1[j])) +
                        (imag(vec1[j]) * imag(vec1[j]));
        double rdiff = real(vec2[j]) - real(vec1[j]);
        double idiff = imag(vec2[j]) - imag(vec1[j]);
        cout << setw(WIDTH) << real(vec1[j]) << ",";
        cout << setw(WIDTH) << imag(vec1[j]) << "  ";
        cout << setw(WIDTH) << real(vec2[j]) << ",";
        cout << setw(WIDTH) << imag(vec2[j]) << "  ";
        cout << setw(WIDTH) << rdiff << ",";
        cout << setw(WIDTH) << idiff << endl;
        double errsq = (rdiff * rdiff) + (idiff + idiff);
        if (errsq > errsqMax) errsqMax = errsq;
    }
    cout << "Max error = " << errsqMax << endl;
    cout << "xform_energy = ";
    cout << xform_energy / sample_energy;
    cout << " times sample_energy\n";
  return 0;
}